title: Emma Bonutti Dâ€™Agostini
url: "https://emmabouttidagostini.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://emmabouttidagostini.github.io"
footer_text: "Emma Bonutti D'Agostini, PhD Candidate in Sociology<br>Last update: January 2026."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Publications"
   link: "/publications"
 - name: "Working Projects"
   link: "/projects"
 - name: "CV"
   link: "BONUTTI D'AGOSTINI-CV-2025.12.pdf"
 - name: "Teaching"
   link: "/teaching"
 - name: "Resources"
   link: "/resources"
 - name: "Contact"
   link: "/contact"

plugins:
  - jekyll-sitemap
